FROM node:18.16.0
WORKDIR /app/client
EXPOSE 8080
COPY client/package*.json /app/client
RUN npm install
COPY client /app/client
RUN npm run build 
RUN rm -rf node_modules
RUN rm -rf src
WORKDIR /app
COPY package*.json /app
RUN npm install 
COPY . /app
ENTRYPOINT ["npm", "start"]